name: PowerShell script
author: Laberit Sistemas S.L.
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  actor:
    description: The GitHub actor running the action
    required: false
    default: ${{ github.actor }}
  token:
    description: The GitHub token running the action
    required: false
    default: ${{ github.token }}
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '7b7d'
  projects:
    description: Projects to deploy
    required: false
    default: ''
  deploymentType:
    description: Type of target of deployment (LocalContainer or OnPrem)
    required: true
  environmentName:
    description: Name of environment to deploy to
    required: true
  tenant:
    description: Name of tenant to deploy to
    required: false
    default: 'default'
  artifacts:
    description: Artifacts to deploy
    required: true
  type:
    description: Type of deployment (CD or Publish)
    required: false
    default: 'CD'
  syncMode:
    description: Schema syncMode
    required: false
    default: 'Add'
runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      env:
        _actor: ${{ inputs.actor }}
        _token: ${{ inputs.token }}
        _parentTelemetryScopeJson: ${{ inputs.parentTelemetryScopeJson }}
        _projects: ${{ inputs.projects }}
        _deploymentType: ${{ inputs.deploymentType }}
        _environmentName: ${{ inputs.environmentName }}
        _tenant: ${{ inputs.tenant }}
        _artifacts: ${{ inputs.artifacts }}
        _type: ${{ inputs.type }}
        _syncMode: ${{ inputs.syncMode }}
      run: try { ${{ github.action_path }}/DeployOnPrem.ps1 -actor $ENV:_actor -token $ENV:_token -parentTelemetryScopeJson $ENV:_parentTelemetryScopeJson -projects $ENV:_projects -deploymentType $ENV:_deploymentType -environmentName $ENV:_environmentName -tenant $ENV:_tenant -artifacts $ENV:_artifacts -type $ENV:_type -syncMode $ENV:_syncMode } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message.Replace("`r",'').Replace("`n",' ')))"; exit 1 }
branding:
  icon: terminal
  color: blue
